### ISSUE TITLE
when we use TypeScript Support there are no saveSVG () and toSVGText () methods

### ISSUE THREAD

**Issue by rprokopenko** [ushelp/EasyQRCodeJS-NodeJS#19]
Hi, when we use TypeScript Support there are no saveSVG () and toSVGText () methods.
![Screenshot_5](https://user-images.githubusercontent.com/64587009/126625452-18470abb-143b-4de6-86c5-d1c3800589cd.png)

**Comment by ushelp** [comment]
Thanks for your feedback.

We released a new version 4.3.3, please upgrade to the latest version.

**Comment by rprokopenko** [comment]
These methods appeared, but they still do not work if you insert a logo. I described it here: #18

**Comment by rprokopenko** [comment]
> Thanks for your feedback.
> 
> We released a new version 4.3.3, please upgrade to the latest version.

These methods appeared, but they still do not work if you insert a logo. I described it here: #18
